# Generated by Django 4.2.1 on 2023-06-07 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New', max_length=50, verbose_name='Название')),
                ('link', models.CharField(default='#', max_length=250, verbose_name='Ссылка на документ')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('day', models.CharField(choices=[('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31')], default='01', max_length=2, verbose_name='День')),
                ('month', models.CharField(choices=[('01', 'Января'), ('02', 'Февраля'), ('03', 'Марта'), ('04', 'Апреля'), ('05', 'Мая'), ('06', 'Июня'), ('07', 'Июля'), ('08', 'Августа'), ('09', 'Сентября'), ('10', 'Октября'), ('11', 'Ноября'), ('12', 'Декабря')], default='01', max_length=2, verbose_name='Месяц')),
                ('year', models.PositiveSmallIntegerField(default=2023, verbose_name='Год')),
                ('timeHour', models.CharField(choices=[('00', '00'), ('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23')], default='00', max_length=2, verbose_name='Час начала')),
                ('timeMinute', models.CharField(choices=[('00', '00'), ('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('46', '46'), ('47', '47'), ('48', '48'), ('49', '49'), ('50', '50'), ('51', '51'), ('52', '52'), ('53', '53'), ('54', '54'), ('55', '55'), ('56', '56'), ('57', '57'), ('58', '58'), ('59', '59')], default='00', max_length=2, verbose_name='Минута начала')),
                ('place', models.CharField(max_length=250, verbose_name='Место проведения')),
                ('place_link', models.CharField(max_length=250, verbose_name='Ссылка на место')),
                ('guest', models.PositiveSmallIntegerField(verbose_name='Количество гостей')),
                ('timeDuration', models.PositiveSmallIntegerField(verbose_name='Длительность мероприятия')),
                ('dress_style', models.CharField(max_length=40, verbose_name='Дресс-код')),
                ('price', models.IntegerField(verbose_name='Новая Цена')),
                ('procents', models.IntegerField(verbose_name='Скидка Процентов')),
                ('link1', models.CharField(default='0', max_length=250, verbose_name='Ссылка на подробнее')),
                ('link2', models.CharField(default='0', max_length=250, verbose_name='Ссылка на подробнее')),
                ('link3', models.CharField(default='0', max_length=250, verbose_name='Ссылка на подробнее')),
                ('link4', models.CharField(default='0', max_length=250, verbose_name='Ссылка на подробнее')),
                ('link5', models.CharField(default='0', max_length=250, verbose_name='Ссылка на подробнее')),
                ('link6', models.CharField(default='0', max_length=250, verbose_name='Ссылка на подробнее')),
                ('link7', models.CharField(default='0', max_length=250, verbose_name='Ссылка на подробнее')),
                ('link8', models.CharField(default='0', max_length=250, verbose_name='Ссылка на подробнее')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New', max_length=50, verbose_name='Название')),
                ('description', models.CharField(max_length=250, verbose_name='Описание вакансии')),
                ('salary', models.IntegerField(verbose_name='Заработная плата')),
                ('salaryDesc', models.CharField(default='смена', max_length=25, verbose_name='Время заработка')),
                ('link', models.CharField(default='https://t.me/chausmoscow_bot', max_length=250, verbose_name='Ссылка на вакансию')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.CreateModel(
            name='lendingLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='name', max_length=50, verbose_name='Название')),
                ('link1', models.CharField(default='#', max_length=250, verbose_name='Ссылка баннер')),
                ('link2', models.CharField(default='#', max_length=250, verbose_name='Ссылка ноутбук')),
            ],
            options={
                'verbose_name': 'Ссылки на странице',
                'verbose_name_plural': 'Ссылки',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New', max_length=50, verbose_name='Название')),
                ('link', models.CharField(default='#', max_length=250, verbose_name='Ссылка на партнера')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
            },
        ),
    ]
