# Generated by Django 4.2.1 on 2023-06-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_selectorphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectorphoto',
            name='title',
            field=models.CharField(default='Блок с фотографиями №', max_length=250, verbose_name='Ссылка на фото'),
        ),
    ]
