# Generated by Django 4.2.1 on 2023-06-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_event_data_event_day_event_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='day',
        ),
        migrations.RemoveField(
            model_name='event',
            name='month',
        ),
        migrations.RemoveField(
            model_name='event',
            name='timeHour',
        ),
        migrations.RemoveField(
            model_name='event',
            name='timeMinute',
        ),
        migrations.RemoveField(
            model_name='event',
            name='year',
        ),
        migrations.AddField(
            model_name='event',
            name='dataTime',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время начала'),
        ),
    ]
