# Generated by Django 4.2.1 on 2023-06-14 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_event_datatime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='dataTime',
            new_name='data',
        ),
    ]
