# Generated by Django 4.2.1 on 2023-06-15 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_datatime_event_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventlinks',
            options={'verbose_name': 'Описание События', 'verbose_name_plural': 'Описания Событий'},
        ),
        migrations.AlterModelOptions(
            name='lendinglinks',
            options={'verbose_name': 'Ссылки на странице', 'verbose_name_plural': 'Ссылки на странице'},
        ),
        migrations.CreateModel(
            name='GuestList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('email', models.CharField(max_length=255, verbose_name='Почта')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('promo', models.CharField(max_length=20, verbose_name='Промокод')),
                ('cash', models.IntegerField(max_length=6, verbose_name='Сумма')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.event')),
            ],
            options={
                'verbose_name': 'Гость',
                'verbose_name_plural': 'Гости',
            },
        ),
    ]
