# Generated by Django 4.2.1 on 2023-06-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_eventlinks_options_alter_lendinglinks_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestlist',
            name='promo',
            field=models.CharField(max_length=20, null=True, verbose_name='Промокод'),
        ),
    ]
