# Generated by Django 4.2.1 on 2023-06-15 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_photo_options_photo_count_photo_link_album_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_1', models.CharField(default='#', max_length=250, verbose_name='Ссылка на фото 1')),
                ('link_2', models.CharField(default='#', max_length=250, verbose_name='Ссылка на фото 2')),
                ('link_3', models.CharField(default='#', max_length=250, verbose_name='Ссылка на фото 3')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.event')),
            ],
        ),
        migrations.DeleteModel(
            name='SelectorPhoto',
        ),
    ]
