# Generated by Django 4.2.1 on 2023-07-02 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_rename_cash_guestlist_amount_remove_guestlist_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestlist',
            name='amount',
            field=models.IntegerField(null=True, verbose_name='Сумма'),
        ),
    ]
