# Generated by Django 4.2.1 on 2023-07-02 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_guestlist_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestlist',
            name='event',
            field=models.CharField(max_length=100, null=True, verbose_name='Event'),
        ),
    ]
