# Generated by Django 4.2.1 on 2023-07-02 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_guestlist_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guestlist',
            old_name='event',
            new_name='event_id',
        ),
    ]
