# Generated by Django 4.2.1 on 2023-07-02 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_rename_event_guestlist_event_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guestlist',
            old_name='event_id',
            new_name='event',
        ),
    ]
