# Generated by Django 4.2.1 on 2023-07-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_guestlist_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestlist',
            name='payment_id',
            field=models.IntegerField(null=True, verbose_name='Payment_id'),
        ),
    ]
