# Generated by Django 4.2.1 on 2023-07-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_guestlist_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestlist',
            name='payment_id',
            field=models.CharField(max_length=30, null=True, verbose_name='Payment_id'),
        ),
    ]
