# Generated by Django 4.2.1 on 2023-07-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_guestlist_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestlist',
            name='payment_id',
            field=models.PositiveBigIntegerField(null=True, verbose_name='Payment_id'),
        ),
    ]
