# Generated by Django 4.2.1 on 2023-07-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_guestlist_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestlist',
            name='payment_id',
        ),
        migrations.AddField(
            model_name='guestlist',
            name='order_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
