# Generated by Django 4.2.1 on 2023-07-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_remove_guestlist_payment_id_guestlist_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='link_Album',
            field=models.CharField(default='#', max_length=250, verbose_name='Ссылка на альбом VK'),
        ),
        migrations.AlterField(
            model_name='guestlist',
            name='order_id',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
